In [1]:
import Observables
import numpy as np

In [2]:
import MuChunModel

In [3]:
commonBounds = (-100,100)
parameterBounds = [commonBounds for i in range(MuChunModel.numberOfParams)]

In [4]:
params=[np.random.uniform(low=bound[0], high=bound[1]) for bound in parameterBounds]

In [5]:
MuChunModel.ELMatrix(params)

[[(0.04228212500171455-0.2243413351900123j),
  (0.9678735518579228-0.6054871395362503j),
  (0.4459757000996837+0.5731228940901916j)],
 [(-0.5248940335808048-0.486573765729833j),
  (-3.062244205259171-1.169048440759952j),
  (-3.734617895545743+0.9556404136787298j)],
 [(-0.2339931141122426+15.29772816163968j),
  (-81.34032825420701-80.60132139055045j),
  (-50.7016079309055+51.61318283843431j)]]

In [6]:
MuChunModel.NLMatrix(params)

[[(-0.0001729286667506921+0.0009891153150977422j),
  (-0.18898573270300112-0.06644284901479956j),
  (14.415293810723494+13.514111874938319j)],
 [(0.0009071091299309241+0.008223914773097312j),
  (-0.945329796427599-1.0484305201730875j),
  (35.62399311808173+35.488339128038064j)],
 [(-0.009696412023190423+0.0034601470529961754j),
  (0.9288265965645307+0.7840835252503744j),
  (32.45505331823105+38.77131555282418j)]]

In [7]:
def MnuMatrix(params):
    return -1 * np.dot(np.dot(np.transpose(MuChunModel.NLMatrix(params)), np.linalg.inv(MuChunModel.NNMatrix(params))), MuChunModel.NLMatrix(params))

In [8]:
MnuMatrix(params)

array([[-2.14078419e-06+1.00346569e-07j,  2.59481564e-04-2.52884724e-04j,
        -1.17868500e-02+9.19738758e-03j],
       [ 2.59481564e-04-2.52884724e-04j, -1.02334506e-02+5.37125700e-02j,
         1.03006589e-01-1.96845031e+00j],
       [-1.17868500e-02+9.19738758e-03j,  1.03006589e-01-1.96845031e+00j,
        -1.57948283e+00+1.10123370e+02j]])

In [9]:
testCKM=Observables.GeneralCKMSystem(MuChunModel.ELMatrix,MnuMatrix,MuChunModel.numberOfParams)

In [10]:
testCKM(params)

array([3.23417813e-02, 6.95789993e-01, 7.46189346e-02, 6.25564701e-01,
       3.08077361e+00, 1.36380307e+02, 1.08745721e-07, 1.98660441e-02,
       1.10169984e+02])

In [11]:
testCKM.Calculate(params,printResult=True)

YuN: 
 [[ 4.22821250e-02 -0.22434134j  9.67873552e-01 -0.60548714j
   4.45975700e-01 +0.57312289j]
 [-5.24894034e-01 -0.48657377j -3.06224421e+00 -1.16904844j
  -3.73461790e+00 +0.95564041j]
 [-2.33993114e-01+15.29772816j -8.13403283e+01-80.60132139j
  -5.07016079e+01+51.61318284j]]
YdN: 
 [[-2.14078419e-06+1.00346569e-07j  2.59481564e-04-2.52884724e-04j
  -1.17868500e-02+9.19738758e-03j]
 [ 2.59481564e-04-2.52884724e-04j -1.02334506e-02+5.37125700e-02j
   1.03006589e-01-1.96845031e+00j]
 [-1.17868500e-02+9.19738758e-03j  1.03006589e-01-1.96845031e+00j
  -1.57948283e+00+1.10123370e+02j]]
Ru: 
 [[ 0.94539517-0.j          0.30607069-0.j         -0.112021  -0.j        ]
 [ 0.17132355-0.05826637j -0.31650068+0.40194661j  0.58111312+0.60648747j]
 [-0.23577075-0.13376621j  0.58751333+0.54718833j -0.38453432+0.36614907j]]
Mu: 
 [  0.6255647    3.08077361 136.3803073 ]
Rd: 
 [[ 9.99985951e-01-0.00000000e+00j -5.29907586e-03-0.00000000e+00j
   1.35741728e-04-0.00000000e+00j]
 [ 5.29281924e-03+2

array([3.23417813e-02, 6.95789993e-01, 7.46189346e-02, 6.25564701e-01,
       3.08077361e+00, 1.36380307e+02, 1.08745721e-07, 1.98660441e-02,
       1.10169984e+02])

In [12]:
testPMNSSystemNew=Observables.PMNSSeeSawSystem(MuChunModel.ELMatrix,MuChunModel.NLMatrix,MuChunModel.NNMatrix,MuChunModel.numberOfParams)

In [13]:
import fit

In [14]:
testFitCKM = fit.Observables(MuChunModel.ELMatrix,MuChunModel.NLMatrix,MuChunModel.NNMatrix,MuChunModel.numberOfParams)

In [15]:
testFitCKM.CalObservablesPrint(params)

MEL [[ 4.22821250e-02 -0.22434134j  9.67873552e-01 -0.60548714j
   4.45975700e-01 +0.57312289j]
 [-5.24894034e-01 -0.48657377j -3.06224421e+00 -1.16904844j
  -3.73461790e+00 +0.95564041j]
 [-2.33993114e-01+15.29772816j -8.13403283e+01-80.60132139j
  -5.07016079e+01+51.61318284j]]
MNL [[-1.72928667e-04+9.89115315e-04j -1.88985733e-01-6.64428490e-02j
   1.44152938e+01+1.35141119e+01j]
 [ 9.07109130e-04+8.22391477e-03j -9.45329796e-01-1.04843052e+00j
   3.56239931e+01+3.54883391e+01j]
 [-9.69641202e-03+3.46014705e-03j  9.28826597e-01+7.84083525e-01j
   3.24550533e+01+3.87713156e+01j]]
MNN [[ 2.48028072e-03+0.j  6.57448952e-01+0.j -6.50254308e+01+0.j]
 [ 6.57448952e-01+0.j -3.23086270e+01+0.j -4.10572243e-01+0.j]
 [-6.50254308e+01+0.j -4.10572243e-01+0.j  3.05216617e-03+0.j]]
Mnunu [[ 2.23653056e-04+0.j         -1.93349627e-02+0.02226579j
   1.03198899e+00-1.28396527j]
 [-1.93349627e-02-0.02226579j  3.88839687e+00+0.j
  -2.17041870e+02+8.24891j   ]
 [ 1.03198899e+00+1.28396527j -2.17041870

array([3.23417813e-02, 6.95789993e-01, 7.46189346e-02, 3.25159329e-08,
       2.03054420e-01, 2.25895782e-02])

In [16]:
testCKM(params)

array([3.23417813e-02, 6.95789993e-01, 7.46189346e-02, 6.25564701e-01,
       3.08077361e+00, 1.36380307e+02, 1.08745721e-07, 1.98660441e-02,
       1.10169984e+02])

In [17]:
testPMNSSystemNew(params)


[0.03234178130151038,
 0.695789993018539,
 0.07461893456573516,
 3.251593290729311e-08,
 0.20305442043892313,
 0.022589578184117092]

In [18]:
testWholeSystem=Observables.CKMPMNSSeeSawSystem(MuChunModel.ELMatrix,MnuMatrix,MuChunModel.ELMatrix,MuChunModel.NLMatrix,MuChunModel.NNMatrix,MuChunModel.numberOfParams)

In [19]:
testWholeSystem(params)

array([3.23417813e-02, 6.95789993e-01, 7.46189346e-02, 2.03054420e-01,
       2.25895782e-02, 5.47394944e-06, 1.80321748e-04, 3.23417813e-02,
       6.95789993e-01, 7.46189346e-02, 3.25159329e-08, 2.03054420e-01,
       2.25895782e-02])

In [20]:
testCKM(params)

array([3.23417813e-02, 6.95789993e-01, 7.46189346e-02, 6.25564701e-01,
       3.08077361e+00, 1.36380307e+02, 1.08745721e-07, 1.98660441e-02,
       1.10169984e+02])

In [21]:
testCKM(params)[3]/testCKM(params)[4]

0.20305442043892313

In [22]:
testPMNSSystemNew(params)

[0.03234178130151038,
 0.695789993018539,
 0.07461893456573516,
 3.251593290729311e-08,
 0.20305442043892313,
 0.022589578184117092]

In [23]:
testWholeSystem.Print(params)

Observabls Result:
Quark:
Qs12 :  0.03234178130151038
Qs23 :  0.695789993018539
Qs13 :  0.07461893456573516
mURmC :  0.20305442043892313
mCRmT :  0.022589578184117092
mDRmS :  5.473949444963588e-06
mSRmB :  0.00018032174829528305
Lepton:
Ls12 :  0.03234178130151038
Ls23 :  0.695789993018539
Ls13 :  0.07461893456573516
m21Rm31 :  3.251593290729311e-08
mERmMu :  0.20305442043892313
mMuRMTau :  0.022589578184117092
