In [1]:
import os
import sys
from matplotlib import pyplot as plt
nb_dir = os.path.split(os.getcwd())[0]

In [3]:
%run fit modelExample

scan done, current chi-sqr= 219003.11217281065
simplex done, current chi-sqr= 7815.891353459604
Fit Result:
[-1.85037816  0.00260918 -0.47757739  0.87950494]
----------------------------------------------------------
Sigma Away:
s12 :  291.78377321910597
s23 :  14.919165223773657
s13 :  0.0013949148600647006
m21Rm31 :  0.1614583930804962
mERmMu :  6.792521094203185e-05
mMuRMTau :  0.06106757615092555
----------------------------------------------------------
total chi-sqr:  306.92692725218205
===========------------------------------------===========
Observabls Result:
s12 :  0.49089847407446346
s23 :  0.641525603431417
s13 :  0.02205091519304516
m21Rm31 :  0.02989752783908531
mERmMu :  0.0048016483350501885
mMuRMTau :  0.059494237093512516


In [3]:
commonBounds = (-5,5)
tBounds = [
    (-0.3,0.3),        # tr
    (1,1.3)   #ti
]

parameterBoundsWithoutT = [commonBounds for i in range(numberOfParams)]
parameterBounds = parameterBoundsWithoutT + tBounds

initParams = [np.random.uniform(low=bound[0], high=bound[1]) for bound in parameterBounds]
fit = Minuit(costFunction, initParams) 
fit.limits=parameterBounds

In [17]:
fit.scan(10000)

┌─────────────────────────────────────────────────────────────────────────┐
│                                 Scan                                    │
├──────────────────────────────────┬──────────────────────────────────────┤
│ FCN = 3.319e+04                  │             Nfcn = 19926             │
│ EDM = 1.66e+04 (Goal: 0.1)       │            time = 3.4 sec            │
├──────────────────────────────────┼──────────────────────────────────────┤
│         INVALID Minimum          │   ABOVE EDM threshold (goal x 10)    │
├──────────────────────────────────┼──────────────────────────────────────┤
│      No parameters at limit      │           Below call limit           │
├──────────────────────────────────┼──────────────────────────────────────┤
│          Hesse not run           │            NO covariance             │
└──────────────────────────────────┴──────────────────────────────────────┘
┌───┬──────┬───────────┬───────────┬────────────┬────────────┬─────────┬─────────┬───────┐
│   │ Name │   Value   │ Hesse Err │ Minos Err- │ Minos Err+ │ Limit-  │ Limit+  │ Fixed │
├───┼──────┼───────────┼───────────┼────────────┼────────────┼─────────┼─────────┼───────┤
│ 0 │ x0   │  1.6667   │  0.0007   │            │            │   -5    │    5    │       │
│ 1 │ x1   │  -1.667   │   0.007   │            │            │   -5    │    5    │       │
│ 2 │ x2   │  -0.0333  │  0.0029   │            │            │  -0.3   │   0.3   │       │
│ 3 │ x3   │  1.2333   │  0.0012   │            │            │    1    │   1.3   │       │
└───┴──────┴───────────┴───────────┴────────────┴────────────┴─────────┴─────────┴───────┘

In [18]:
fit.simplex()

┌─────────────────────────────────────────────────────────────────────────┐
│                               Simplex                                   │
├──────────────────────────────────┬──────────────────────────────────────┤
│ FCN = 195.2                      │             Nfcn = 20076             │
│ EDM = 651 (Goal: 0.1)            │                                      │
├──────────────────────────────────┼──────────────────────────────────────┤
│         INVALID Minimum          │   ABOVE EDM threshold (goal x 10)    │
├──────────────────────────────────┼──────────────────────────────────────┤
│      No parameters at limit      │           Below call limit           │
├──────────────────────────────────┼──────────────────────────────────────┤
│          Hesse not run           │            NO covariance             │
└──────────────────────────────────┴──────────────────────────────────────┘
┌───┬──────┬───────────┬───────────┬────────────┬────────────┬─────────┬─────────┬───────┐
│   │ Name │   Value   │ Hesse Err │ Minos Err- │ Minos Err+ │ Limit-  │ Limit+  │ Fixed │
├───┼──────┼───────────┼───────────┼────────────┼────────────┼─────────┼─────────┼───────┤
│ 0 │ x0   │  1.73004  │  0.00019  │            │            │   -5    │    5    │       │
│ 1 │ x1   │  -0.259   │   0.007   │            │            │   -5    │    5    │       │
│ 2 │ x2   │ 144.3e-3  │  0.6e-3   │            │            │  -0.3   │   0.3   │       │
│ 3 │ x3   │  1.1462   │  0.0011   │            │            │    1    │   1.3   │       │
└───┴──────┴───────────┴───────────┴────────────┴────────────┴─────────┴─────────┴───────┘

In [19]:
fit.migrad(None,2000)

┌─────────────────────────────────────────────────────────────────────────┐
│                                Migrad                                   │
├──────────────────────────────────┬──────────────────────────────────────┤
│ FCN = 167.3                      │             Nfcn = 88510             │
│ EDM = 9.26e+07 (Goal: 0.0002)    │           time = 31.7 sec            │
├──────────────────────────────────┼──────────────────────────────────────┤
│         INVALID Minimum          │   ABOVE EDM threshold (goal x 10)    │
├──────────────────────────────────┼──────────────────────────────────────┤
│     SOME parameters at limit     │           Below call limit           │
├──────────────────────────────────┼──────────────────────────────────────┤
│             Hesse ok             │         Covariance accurate          │
└──────────────────────────────────┴──────────────────────────────────────┘
┌───┬──────┬───────────┬───────────┬────────────┬────────────┬─────────┬─────────┬───────┐
│   │ Name │   Value   │ Hesse Err │ Minos Err- │ Minos Err+ │ Limit-  │ Limit+  │ Fixed │
├───┼──────┼───────────┼───────────┼────────────┼────────────┼─────────┼─────────┼───────┤
│ 0 │ x0   │     2     │     7     │            │            │   -5    │    5    │       │
│ 1 │ x1   │    -0     │     7     │            │            │   -5    │    5    │       │
│ 2 │ x2   │    0.1    │    0.4    │            │            │  -0.3   │   0.3   │       │
│ 3 │ x3   │   1.14    │   0.21    │            │            │    1    │   1.3   │       │
└───┴──────┴───────────┴───────────┴────────────┴────────────┴─────────┴─────────┴───────┘
┌────┬─────────────────────────────┐
│    │     x0     x1     x2     x3 │
├────┼─────────────────────────────┤
│ x0 │     22     -0  -0.00 -0.000 │
│ x1 │     -0   24.9  -0.00 -0.000 │
│ x2 │  -0.00  -0.00 0.0702  0.000 │
│ x3 │ -0.000 -0.000  0.000 0.0223 │
└────┴─────────────────────────────┘

In [115]:
np.asarray(fit.values)

array([ 1.73365932, -0.27152867, -0.19283536,  1.08470929])

In [15]:
observables(np.asarray(fit.values))

array([0.23479212, 0.49643985, 0.01439682, 0.03634365, 0.00468463,
       0.05700125])

In [116]:
for i in range(10):
    initParams = [np.random.uniform(low=bound[0], high=bound[1]) for bound in parameterBounds]
    fit.values = initParams
    fit.scan(10000)
    fit.simplex()
    fit.migrad()
    print(fit.values,"\n",costFunction(np.asarray(fit.values)))

<ValueView x0=1.7336591640642123 x1=0.2715243517559154 x2=-0.19283680658717933 x3=1.0847029349067052> 
 19.03294928099922
<ValueView x0=1.7336593400271658 x1=0.27153017586674455 x2=-0.19283461587999162 x3=1.0847098551246228> 
 19.032941923998557
<ValueView x0=1.7304425049078436 x1=0.2712162620110803 x2=-0.1926731795495631 x3=1.0848585667261372> 
 18.791535901818847
<ValueView x0=1.7304429309615674 x1=0.27120196283607 x2=-0.19267141279926747 x3=1.0848874823118824> 
 18.791353181165444
<ValueView x0=1.7336593517979075 x1=0.271529348462094 x2=0.19283293146072694 x3=1.0847087459693698> 
 19.03294373684061
<ValueView x0=1.7336593066366923 x1=0.27153911555287813 x2=0.19283672868392027 x3=1.0847104561010488> 
 19.032946664628113
<ValueView x0=1.733659248940759 x1=0.2715476545322302 x2=-0.19283556053063095 x3=1.0847023921677246> 
 19.03295872872132
<ValueView x0=1.7336592822206374 x1=0.2715318519319858 x2=0.19283374491671595 x3=1.084709439881914> 
 19.032943064396456
<ValueView x0=1.7304428342