In [1]:
import os
import sys
from matplotlib import pyplot as plt
nb_dir = os.path.split(os.getcwd())[0]

In [2]:
%run fit modelExample

scan done, current chi-sqr= 219003.11213451554
simplex done, current chi-sqr= 5318.905723021406
1 loop is done
Fit Result:
[-1.85037608  0.00260821 -0.4775778   0.87950473]
----------------------------------------------------------
Sigma Away:
s12 :  291.7831515866748
s23 :  14.919310144529232
s13 :  0.0013918447865818402
m21Rm31 :  0.16219557202598414
mERmMu :  7.918096963760163e-10
mMuRMTau :  0.060809630293249074
----------------------------------------------------------
total chi-sqr:  306.9268587791017
===============----------------------------===============
Observabls Result:
s12 :  0.4908982739196602
s23 :  0.6415259411070966
s13 :  0.02205089216420269
m21Rm31 :  0.02989829749573642
mERmMu :  0.004799994372177343
mMuRMTau :  0.05949319217468751


In [5]:
fit.migrad(None,5)

┌─────────────────────────────────────────────────────────────────────────┐
│                                Migrad                                   │
├──────────────────────────────────┬──────────────────────────────────────┤
│ FCN = 5.785e+04                  │              Nfcn = 380              │
│ EDM = 1.65e-07 (Goal: 0.0002)    │                                      │
├──────────────────────────────────┼──────────────────────────────────────┤
│          Valid Minimum           │   Below EDM threshold (goal x 10)    │
├──────────────────────────────────┼──────────────────────────────────────┤
│     SOME parameters at limit     │           Below call limit           │
├──────────────────────────────────┼──────────────────────────────────────┤
│             Hesse ok             │         Covariance accurate          │
└──────────────────────────────────┴──────────────────────────────────────┘
┌───┬──────┬───────────┬───────────┬────────────┬────────────┬─────────┬─────────┬───────┐
│   │ Name │   Value   │ Hesse Err │ Minos Err- │ Minos Err+ │ Limit-  │ Limit+  │ Fixed │
├───┼──────┼───────────┼───────────┼────────────┼────────────┼─────────┼─────────┼───────┤
│ 0 │ x0   │  1.73316  │  0.00006  │            │            │   -20   │   20    │       │
│ 1 │ x1   │  -0.288   │   0.010   │            │            │   -20   │   20    │       │
│ 2 │ x2   │-400.0000e-3│ 0.0009e-3 │            │            │  -0.5   │  -0.4   │       │
│ 3 │ x3   │ 933.45e-3 │  0.25e-3  │            │            │0.866025 │  0.95   │       │
└───┴──────┴───────────┴───────────┴────────────┴────────────┴─────────┴─────────┴───────┘
┌────┬─────────────────────────────────────────────┐
│    │         x0         x1         x2         x3 │
├────┼─────────────────────────────────────────────┤
│ x0 │   3.52e-09  -374.0e-9   1.18e-21     0.1e-9 │
│ x1 │  -374.0e-9    9.5e-05  97.19e-21          0 │
│ x2 │   1.18e-21  97.19e-21    5.1e-23 540.62e-21 │
│ x3 │     0.1e-9          0 540.62e-21   6.44e-08 │
└────┴─────────────────────────────────────────────┘

In [22]:
fit.scan()

┌─────────────────────────────────────────────────────────────────────────┐
│                                 Scan                                    │
├──────────────────────────────────┬──────────────────────────────────────┤
│ FCN = 2.187e+04                  │             Nfcn = 1052              │
│ EDM = 1.67e+04 (Goal: 0.1)       │            time = 0.1 sec            │
├──────────────────────────────────┼──────────────────────────────────────┤
│         INVALID Minimum          │   ABOVE EDM threshold (goal x 10)    │
├──────────────────────────────────┼──────────────────────────────────────┤
│      No parameters at limit      │           Below call limit           │
├──────────────────────────────────┼──────────────────────────────────────┤
│          Hesse not run           │            NO covariance             │
└──────────────────────────────────┴──────────────────────────────────────┘
┌───┬──────┬───────────┬───────────┬────────────┬────────────┬─────────┬─────────┬───────┐
│   │ Name │   Value   │ Hesse Err │ Minos Err- │ Minos Err+ │ Limit-  │ Limit+  │ Fixed │
├───┼──────┼───────────┼───────────┼────────────┼────────────┼─────────┼─────────┼───────┤
│ 0 │ x0   │  -2.924   │   0.018   │            │            │   -20   │   20    │       │
│ 1 │ x1   │  -2.2e-3  │  0.6e-3   │            │            │   -20   │   20    │       │
│ 2 │ x2   │-401.10e-3 │  0.29e-3  │            │            │  -0.5   │  -0.4   │       │
│ 3 │ x3   │ 929.01e-3 │  0.25e-3  │            │            │0.866025 │  0.95   │       │
└───┴──────┴───────────┴───────────┴────────────┴────────────┴─────────┴─────────┴───────┘

In [107]:
print(fit.values)
fit.migrad(None,500)
print(fit.values)
fitResult1=np.asarray(fit.values)
fitChi1=costFunction(fitResult1)
fit.reset()
print(fit.values)
fit.values=np.asarray(fitResult1)
print(fit.values)
fit.migrad(None,500)
print(fit.values)
fitResult2=np.asarray(fit.values)
fitChi2=costFunction(fitResult2)

<ValueView x0=-2.519808910959897 x1=0.03445257010160674 x2=0.2999999999999999 x3=1.0>
<ValueView x0=-2.51980927657983 x1=0.034452604986583424 x2=0.3 x3=1.0>
<ValueView x0=-2.519809276564639 x1=0.03445260498402192 x2=0.3 x3=1.0>
<ValueView x0=-2.51980927657983 x1=0.034452604986583424 x2=0.3 x3=1.0>
<ValueView x0=-2.5198089109593615 x1=0.03445257010199487 x2=0.2999999999999999 x3=1.0>


In [97]:
costFunction(fit.values)

41880.714900186686

In [43]:
commonBounds = (-5,5)
tBounds = [
    (-0.3,0.3),        # tr
    (1,1.3)   #ti
]

parameterBoundsWithoutT = [commonBounds for i in range(numberOfParams)]
parameterBounds = parameterBoundsWithoutT + tBounds

initParams = [np.random.uniform(low=bound[0], high=bound[1]) for bound in parameterBounds]
fit = Minuit(costFunction, initParams) 
fit.limits=parameterBounds

In [17]:
fit.scan(10000)

┌─────────────────────────────────────────────────────────────────────────┐
│                                 Scan                                    │
├──────────────────────────────────┬──────────────────────────────────────┤
│ FCN = 3.319e+04                  │             Nfcn = 19926             │
│ EDM = 1.66e+04 (Goal: 0.1)       │            time = 3.4 sec            │
├──────────────────────────────────┼──────────────────────────────────────┤
│         INVALID Minimum          │   ABOVE EDM threshold (goal x 10)    │
├──────────────────────────────────┼──────────────────────────────────────┤
│      No parameters at limit      │           Below call limit           │
├──────────────────────────────────┼──────────────────────────────────────┤
│          Hesse not run           │            NO covariance             │
└──────────────────────────────────┴──────────────────────────────────────┘
┌───┬──────┬───────────┬───────────┬────────────┬────────────┬─────────┬─────────┬───────┐
│   │ Name │   Value   │ Hesse Err │ Minos Err- │ Minos Err+ │ Limit-  │ Limit+  │ Fixed │
├───┼──────┼───────────┼───────────┼────────────┼────────────┼─────────┼─────────┼───────┤
│ 0 │ x0   │  1.6667   │  0.0007   │            │            │   -5    │    5    │       │
│ 1 │ x1   │  -1.667   │   0.007   │            │            │   -5    │    5    │       │
│ 2 │ x2   │  -0.0333  │  0.0029   │            │            │  -0.3   │   0.3   │       │
│ 3 │ x3   │  1.2333   │  0.0012   │            │            │    1    │   1.3   │       │
└───┴──────┴───────────┴───────────┴────────────┴────────────┴─────────┴─────────┴───────┘

In [18]:
fit.simplex()

┌─────────────────────────────────────────────────────────────────────────┐
│                               Simplex                                   │
├──────────────────────────────────┬──────────────────────────────────────┤
│ FCN = 195.2                      │             Nfcn = 20076             │
│ EDM = 651 (Goal: 0.1)            │                                      │
├──────────────────────────────────┼──────────────────────────────────────┤
│         INVALID Minimum          │   ABOVE EDM threshold (goal x 10)    │
├──────────────────────────────────┼──────────────────────────────────────┤
│      No parameters at limit      │           Below call limit           │
├──────────────────────────────────┼──────────────────────────────────────┤
│          Hesse not run           │            NO covariance             │
└──────────────────────────────────┴──────────────────────────────────────┘
┌───┬──────┬───────────┬───────────┬────────────┬────────────┬─────────┬─────────┬───────┐
│   │ Name │   Value   │ Hesse Err │ Minos Err- │ Minos Err+ │ Limit-  │ Limit+  │ Fixed │
├───┼──────┼───────────┼───────────┼────────────┼────────────┼─────────┼─────────┼───────┤
│ 0 │ x0   │  1.73004  │  0.00019  │            │            │   -5    │    5    │       │
│ 1 │ x1   │  -0.259   │   0.007   │            │            │   -5    │    5    │       │
│ 2 │ x2   │ 144.3e-3  │  0.6e-3   │            │            │  -0.3   │   0.3   │       │
│ 3 │ x3   │  1.1462   │  0.0011   │            │            │    1    │   1.3   │       │
└───┴──────┴───────────┴───────────┴────────────┴────────────┴─────────┴─────────┴───────┘

In [7]:
fit.migrad(None,2000)

┌─────────────────────────────────────────────────────────────────────────┐
│                                Migrad                                   │
├──────────────────────────────────┬──────────────────────────────────────┤
│ FCN = 4.188e+04                  │              Nfcn = 124              │
│ EDM = 4.88e-07 (Goal: 0.0002)    │                                      │
├──────────────────────────────────┼──────────────────────────────────────┤
│          Valid Minimum           │   Below EDM threshold (goal x 10)    │
├──────────────────────────────────┼──────────────────────────────────────┤
│     SOME parameters at limit     │           Below call limit           │
├──────────────────────────────────┼──────────────────────────────────────┤
│             Hesse ok             │         Covariance accurate          │
└──────────────────────────────────┴──────────────────────────────────────┘
┌───┬──────┬───────────┬───────────┬────────────┬────────────┬─────────┬─────────┬───────┐
│   │ Name │   Value   │ Hesse Err │ Minos Err- │ Minos Err+ │ Limit-  │ Limit+  │ Fixed │
├───┼──────┼───────────┼───────────┼────────────┼────────────┼─────────┼─────────┼───────┤
│ 0 │ x0   │  -2.520   │   0.004   │            │            │   -5    │    5    │       │
│ 1 │ x1   │  0.0345   │  0.0014   │            │            │   -5    │    5    │       │
│ 2 │ x2   │300.000e-3 │ 0.005e-3  │            │            │  -0.3   │   0.3   │       │
│ 3 │ x3   │ 1.000000  │ 0.000005  │            │            │    1    │   1.3   │       │
└───┴──────┴───────────┴───────────┴────────────┴────────────┴─────────┴─────────┴───────┘
┌────┬─────────────────────────────────────────────┐
│    │         x0         x1         x2         x3 │
├────┼─────────────────────────────────────────────┤
│ x0 │   1.99e-05     0.3e-6 -4.400e-15 -3.838e-15 │
│ x1 │     0.3e-6   2.09e-06    461e-18  0.681e-15 │
│ x2 │ -4.400e-15    461e-18   6.37e-18      0e-18 │
│ x3 │ -3.838e-15  0.681e-15      0e-18    1.5e-17 │
└────┴─────────────────────────────────────────────┘

In [115]:
np.asarray(fit.values)

array([ 1.73365932, -0.27152867, -0.19283536,  1.08470929])

In [15]:
observables(np.asarray(fit.values))

array([0.23479212, 0.49643985, 0.01439682, 0.03634365, 0.00468463,
       0.05700125])

In [116]:
for i in range(10):
    initParams = [np.random.uniform(low=bound[0], high=bound[1]) for bound in parameterBounds]
    fit.values = initParams
    fit.scan(10000)
    fit.simplex()
    fit.migrad()
    print(fit.values,"\n",costFunction(np.asarray(fit.values)))

<ValueView x0=1.7336591640642123 x1=0.2715243517559154 x2=-0.19283680658717933 x3=1.0847029349067052> 
 19.03294928099922
<ValueView x0=1.7336593400271658 x1=0.27153017586674455 x2=-0.19283461587999162 x3=1.0847098551246228> 
 19.032941923998557
<ValueView x0=1.7304425049078436 x1=0.2712162620110803 x2=-0.1926731795495631 x3=1.0848585667261372> 
 18.791535901818847
<ValueView x0=1.7304429309615674 x1=0.27120196283607 x2=-0.19267141279926747 x3=1.0848874823118824> 
 18.791353181165444
<ValueView x0=1.7336593517979075 x1=0.271529348462094 x2=0.19283293146072694 x3=1.0847087459693698> 
 19.03294373684061
<ValueView x0=1.7336593066366923 x1=0.27153911555287813 x2=0.19283672868392027 x3=1.0847104561010488> 
 19.032946664628113
<ValueView x0=1.733659248940759 x1=0.2715476545322302 x2=-0.19283556053063095 x3=1.0847023921677246> 
 19.03295872872132
<ValueView x0=1.7336592822206374 x1=0.2715318519319858 x2=0.19283374491671595 x3=1.084709439881914> 
 19.032943064396456
<ValueView x0=1.7304428342